### ISSUE TITLE
Path or pattern "bower_components/sinonjs/sinon.js" did not match any files

### ISSUE THREAD

**Issue by jamesarosen** [csantero/ember-sinon#17]
```json
// package.json:
"ember-sinon": "0.2.1",
```

Console:
```
Error: Path or pattern "bower_components/sinonjs/sinon.js" did not match any files
    at Object.multiGlob (/Users/me/Code/MyApp/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/me/Code/MyApp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/me/Code/MyApp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/me/Code/MyApp/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/me/Code/MyApp/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/me/Code/MyApp/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/me/Code/MyApp/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/me/Code/MyApp/node_modules/rsvp/dist/rsvp.js:1290:9)
```

Possibly related to rwjblue/ember-cli-ic-ajax#11

**Comment by csantero** [comment]
Is this with ember-cli master? I've been using ember-sinon 0.2.1 with ember-cli 0.2.7 for a while now.

**Comment by jamesarosen** [comment]
It was 0.2.7. I had upgraded a whole bunch of libraries at the same time. I'll try it in isolation to see if that makes a difference.

**Comment by jamesarosen** [comment]
The problem is that I had
```
"sinon": "http://sinonjs.org/releases/sinon-1.12.2.js",
```
in my `bower.json` instead of the newer
```
"sinonjs": "~1.14.1"
```
