### ISSUE TITLE
Installing ember-sinon results in a 404

### ISSUE THREAD

**Issue by chrisvdp** [csantero/ember-sinon#28]
I installed the latest ember-sinon, when I try to init it I get the following.
```
$ ember g ember-sinon
version: 1.13.8
installing ember-sinon
Installing browser packages via Bower...
  not-cached http://sinonjs.org/releases/sinon-1.12.2.js=sinon=http://sinonjs.org/releases/sinon-1.12.2.js#*
Status code of 404
Error: Status code of 404
  at createError (/Users/***/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
  at Request.<anonymous> (/Users/***/node_modules/ember-cli/node_modules/bower/lib/util/download.js:45:40)
  at Request.emit (events.js:129:20)
  at Request.onRequestResponse (/Users/***/node_modules/ember-cli/node_modules/bower/node_modules/request/request.js:1176:10)
  at ClientRequest.emit (events.js:107:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
  at Socket.socketOnData (_http_client.js:310:20)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
```

**Comment by csantero** [comment]
Can you publish a demo repo or set of steps to reproduce this? I tried locally with a new repository and it seems to be working fine.

**Comment by marnen** [comment]
See https://github.com/ember-cli/ember-cli/pull/4643; apparently the syntax changed.
