### ISSUE TITLE
Chained calledWith

### ISSUE THREAD

**Issue by spinlock99** [csantero/ember-sinon#31]
I'm seeing something weird in my tests. When I write:

    expect(spy.calledWith('foo')).to.be.ok;

The test passes. But, when I write:

    expect(spy).to.have.been.calledWith('foo');

I get this error:

    TypeError: (0 , _chai.expect)(...).to.have.been.calledWith is not a function

I've used this syntax before and I do prefer it because it's nicer to read. Any idea why it's not working with `ember-sinon`?

Thanks.

**Comment by csantero** [comment]
I believe `.to.have.been.calledWith` comes from `sinon-chai`. How are you importing that?

**Comment by spinlock99** [comment]
That was the problem. I've installed `sinon-chai` with bower and added this to my `ember-cli-build.js`:

      if (app.tests) {
        app.import('bower_components/sinon-chai/lib/sinon-chai.js', {type: 'test'});
      }

Now all is well.

One odd thing was that I couldn't install `sinon-chai` via npm. When I tried, my `ember-cli-build.js` looked like this:

    if (app.tests) {
      app.import('node_modules/sinon-chai/lib/sinon-chai.js', {type: 'test'});
    }

but I got this error when trying to run `ember test -s`:

  BuildingENOENT: no such file or directory, stat '/Users/dixon/rules-v2/adstage-tables/tmp/concat_with_maps-input_base_path-fXzgn9Jp.tmp/0/node_modules/sinon-chai/lib/sinon-chai.js'
  Error: ENOENT: no such file or directory, stat '/Users/dixon/rules-v2/adstage-tables/tmp/concat_with_maps-input_base_path-fXzgn9Jp.tmp/0/node_modules/sinon-chai/lib/sinon-chai.js'
      at Error (native)
      at Object.fs.statSync (fs.js:892:18)
      at ConcatWithMaps.keyForFile (/Users/dixon/rules-v2/adstage-tables/node_modules/broccoli-caching-writer/index.js:90:20)
      at Array.map (native)
      at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/dixon/rules-v2/adstage-tables/node_modules/broccoli-caching-writer/index.js:112:65)
      at /Users/dixon/rules-v2/adstage-tables/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
      at lib$rsvp$$internal$$tryCatch (/Users/dixon/rules-v2/adstage-tables/node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (/Users/dixon/rules-v2/adstage-tables/node_modules/rsvp/dist/rsvp.js:505:17)
      at lib$rsvp$$internal$$publish (/Users/dixon/rules-v2/adstage-tables/node_modules/rsvp/dist/rsvp.js:476:11)
      at lib$rsvp$asap$$flush (/Users/dixon/rules-v2/adstage-tables/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by csantero** [comment]
I believe ember CLI doesn't support doing app.import directly from node_modules. You would need to return a new broccoli tree that pulls in that directory first, and then you can app.import from there.

**Comment by spinlock99** [comment]
Thanks. I'll give it a try.
